Alert badge components
nisargpawade/falcon-ui-component-library pull request #2
Opened 2022-02-09 19:02 UTC by nisargpawade

- updated links in sidebar
- changed avatar components css code to suit the format like other components
- added alert component
-added badge component
   - on icon
   - on avatar

2022-02-09 19:43 UTC, abhijeetekad approved these changes

2022-02-10 03:55 UTC, prathmeshjagtap requested changes

2022-02-10 03:55 UTC, prathmeshjagtap commented on components/alert/alert.css
> +  background-color: #d6d3d1;
use color variables

2022-02-10 05:09 UTC, nisargpawade commented on components/alert/alert.css
> +  background-color: #d6d3d1;
done

2022-02-10 07:08 UTC, prathmeshjagtap approved these changes

2022-02-10 07:39 UTC, merged